src/Entity/News.php
<?php

namespace App\Entity;

use App\Repository\NewsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NewsRepository::class)
 */
class News
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Create_at;

    /**
     * @ORM\ManyToOne(targetEntity=Tag::class, inversedBy="news")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tag;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->img_path;
    }

    public function setImgPath(string $img_path): self
    {
        $this->img_path = $img_path;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->Create_at;
    }

    public function setCreateAt(\DateTimeInterface $Create_at): self
    {
        $this->Create_at = $Create_at;

        return $this;
    }

    public function getTag(): ?Tag
    {
        return $this->tag;
    }

    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="neon_home")
     */
    public function index(): Response
    {

        // fetching all data from post table to display in home
        $posts = $this->getDoctrine()->getRepository(Post::class)
            ->findAll();

        $users = $this->getDoctrine()->getRepository(User::class)
            ->findAll();


        return $this->render('home/index.html.twig', [
            'posts' => $posts,
            'users' => $users
        ]);
    }
    

    /**
     * @Route("/home/user/{id}", methods={"GET"}, name="neon_user")
     */
    public function showProfile($id): Response
    {
        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id);

        return $this->render('home/user.html.twig', [
            'user' => $user
        ]);

    }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <style>
        ::-webkit-scrollbar {
            display: none;
        }

        .all-wrapper {
            margin: 1em auto;
            width: 98%;
            font: 18px/1.5 sans-serif;
        }

        .all-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }

        .users-wrapper {
            height: 100vh;
            width: 250px;
            background-color: #15baba;
            border-radius: 5px;

        }

        .news-wrapper {
            height: 100vh;
            width: 250px;
            background-color: darkgray;
            border-radius: 5px;

        }

        .post-wrapper {
            overflow-y: auto;
            height: 800px;
            width: 800px;
        }

        .status-wrapper {
            z-index: 50;
            width: 40%;
            margin: 0 auto;
        }
    </style>

    <div class="all-wrapper d-flex justify-content-around">

        {# new #}
        <div class="users-wrapper">
            <div class="status-wrapper d-flex justify-content-center">
                <div class="mr-auto ml-auto position-relative d-flex justify-content-center">
                    <div class="ml-auto mr-auto pt-4 pr-4 pb-4 pl-4" style="background-color: #EFC050;">
                        <a class="text-center text-black" href="{{ path('create_post') }}">Send everyone your status
                            today
                            <span class="text-success">
                    <i class="fa-solid fa-paper-plane"></i>
                </span>
                        </a>
                    </div>
                </div>
            </div>
            <div class="people-wrapper text-center mb-4 mt-4">
                <a href="#" class="text-black">
                    Other people
                    <i class="fa-solid fa-user-group"></i>
                </a>
                {% if app.user %}
                    <ul class="list-group list-group-light overflow-hidden mt-4">
                        {% for user in users %}
                            {% if user.profileImg != app.user.profileImg
                                and user.name != app.user.name and user.email != app.user.email %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="d-flex align-items-center">
                                        <div class="ms-3 d-flex align-content-center">
                                            <img src="{{ user.profileImg }}" alt="Avatar"
                                                 style="width: 35px; height: 35px"
                                                 class="rounded-circle mr-2"/>
                                            <p class="fw-bold mb-0 mt-2" style="font-size: 14px;">{{ user.name }}</p>
                                        </div>
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>


        </div>

        <div class="post-wrapper">

            {% if app.user %}
                {% for post in posts %}
                    <div class="page-content page-container mx-auto mt-4" id="page-content">
                        <div class="padding">
                            <div class="row container d-flex justify-content-center mx-auto">
                                <div class="col-md-8 bg-white rounded postbox">
                                    <div class="box box-widget w-100 bg-white">
                                        <div class="box-header with-border">
                                            <div class="user-block mt-2">
                                                <img class="img-circle rounded-circle img-fluid"
                                                     src="{{ post.user.profileImg }}"
                                                     style="width: 50px; height: 50px"
                                                     alt="User Image"> <span class="username"><a href="#"
                                                                                                 data-abc="true">
                                        {{ post.user.name }}
                                    </a></span> <span class="description">
                                    {{ post.createAt|date('F j, Y, g:i a') }}
                                </span></div>
                                            <div class="box-tools d-flex justify-content-end mb-3">
                                                <a href="{{ path('detail_post', {'id': post.id }) }}"
                                                   class="btn btn-info ml-1 mr-1 text-white">
                                                    Detail
                                                </a>
                                            </div>
                                        </div>
                                        <div class="box-body">
                                            <p>{{ post.description }}</p>
                                            <img class="img-responsive w-100 mt-2 mb-3" src="{{ post.imgPath }}"
                                                 alt="Photo">
                                            <button type="button" class="btn btn-default btn-xs"><i
                                                        class="fa fa-share"></i>
                                                Share
                                            </button>
                                            <button type="button" class="btn btn-default btn-xs"><i
                                                        class="fa fa-thumbs-o-up"></i> Like
                                            </button>
                                            <span class="pull-right text-muted">127 likes - 3 comments</span>
                                            <span class="pull-right text-muted">
                                                <strong> #{{ post.tag.name }}</strong>
                                            </span>
                                        </div>
                                        <div class="box-footer box-comments mt-4 mb-4">
                                        </div>
                                        <div class="box-footer mt-4 mb-4">
                                            <form action="#" method="post"><img class="img-responsive img-circle img-sm"
                                                                                src="https://img.icons8.com/color/36/000000/administrator-male.png"
                                                                                alt="Alt Text">
                                                <div class="img-push"><input type="text" class="form-control input-sm"
                                                                             placeholder="Press enter to post comment">
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        {# tag #}
        <div class="news-wrapper text-center">
            <div class="news bg-dark bg-opacity-50">
                <a href="{{ path('neon_news') }}" class="text-warning">News to day <i
                            class="fa-solid fa-newspaper"></i></a>
            </div>
            <div class="tags bg-info bg-opacity-75">
                <a href="{{ path('neon_tags') }}" class="text-danger text-opacity-50">Hot trend topics <i
                            class="fa-solid fa-hashtag"></i></a>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
    <div>
        {% if user is defined %}
            <section class="vh-100" style="background-color: #eee;">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col-md-12 col-xl-4">
                            <div class="card" style="border-radius: 15px;">
                                <div class="card-body text-center">
                                    <div class="mt-3 mb-4">
                                        <img src="{{ user.profileImg }}"
                                             class="rounded-circle img-fluid"
                                             style="width: 100px; overflow: hidden; height: 100px"/>
                                    </div>
                                    <h4 class="mb-2">{{ user.name }}</h4>
                                    <p class="text-muted mb-4">{{ user.email }} <span class="mx-2">|</span> <a
                                                href="#!">{{ user.birthday|date('F j, Y') }}</a></p>
                                    <div class="mb-4 pb-2">
                                        <button type="button" class="btn btn-outline-primary btn-floating">
                                            <i class="fab fa-facebook-f fa-lg"></i>
                                        </button>
                                        <button type="button" class="btn btn-outline-primary btn-floating">
                                            <i class="fab fa-twitter fa-lg"></i>
                                        </button>
                                        <button type="button" class="btn btn-outline-primary btn-floating">
                                            <i class="fab fa-skype fa-lg"></i>
                                        </button>
                                    </div>
                                    <a class="btn btn-danger" href="{{ path('app_logout') }}"
                                       onclick="return confirm('Are you sure to logout?');">Log out</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        {% endif %}
    </div>
{% endblock %}